[versions]
agp = "8.5.2"
junit = "4.12"
gson = "2.9.0"
msgpack = "0.8.11"
java-websocket = "1.5.3"
vcdiff = "0.1.1"
hamcrest = "1.3"
nanohttpd = "2.3.0"
mockito = "1.10.19"
concurrentunit = "0.4.2"
slf4j = "1.7.30"

[libraries]
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
msgpack = { group = "org.msgpack", name = "msgpack-core", version.ref = "msgpack" }
java-websocket = { group = "org.java-websocket", name = "Java-WebSocket", version.ref = "java-websocket" }
vcdiff-core = { group = "com.davidehrmann.vcdiff", name = "vcdiff-core", version.ref = "vcdiff" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
hamcrest-all = { group = "org.hamcrest", name = "hamcrest-all", version.ref = "hamcrest" }
nanohttpd = { group = "org.nanohttpd", name = "nanohttpd", version.ref = "nanohttpd" }
nanohttpd-nanolets = { group = "org.nanohttpd", name = "nanohttpd-nanolets", version.ref = "nanohttpd" }
nanohttpd-websocket = { group = "org.nanohttpd", name = "nanohttpd-websocket", version.ref = "nanohttpd" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
concurrentunit = { group = "net.jodah", name = "concurrentunit", version.ref = "concurrentunit" }
slf4j-simple = { group = "org.slf4j", name = "slf4j-simple", version.ref = "slf4j" }

[bundles]
common = ["msgpack", "java-websocket", "vcdiff-core"]
tests = ["junit","hamcrest-all", "nanohttpd", "nanohttpd-nanolets", "nanohttpd-websocket", "mockito-core", "concurrentunit", "slf4j-simple"]

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
