name: Emulate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        android-api-level: [ 21, 24, 29, 35 ]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up the JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5
        timeout-minutes: 5

      # API 30+ emulators only have x86_64 system images.
      - id: get-avd-arch
        run: echo "arch=$(if [ ${{ matrix.android-api-level }} -ge 30 ]; then echo x86_64; else echo x86; fi)" >> $GITHUB_OUTPUT

      - name: Enable KVM
        run: |
            echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
            sudo udevadm control --reload-rules
            sudo udevadm trigger --name-match=kvm

      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.android-api-level }}
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          arch: ${{ steps.get-avd-arch.outputs.arch }}
          target: default
          # Print emulator logs if tests fail
          script: ./gradlew :android:connectedAndroidTest ${{ matrix.android-api-level == 19 && '-PhttpURLConnection' || '' }} || (adb logcat -d System.out:I && exit 1)

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: android-build-reports-${{ matrix.android-api-level }}
          path: android/build/reports/
